name: gitaction

on:
  push:
  workflow_dispatch:
    
jobs: 
  genFileAndPush:
    runs-on: macOS-latest

    # Load repo and install R
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: r-lib/actions/setup-r@master
      with:
         r-version: '4.1.2'

    - name: Run R scripts and generate file
      run: |
        saveRDS(1:3, file = "file.rds")
      shell: Rscript {0}
      
    - name: Check Files
      run: ls -lha

    - name: Send files to new repo
      uses: GuillaumeFalourd/git-commit-push@main
      with:
        target_branch: main
        files: file.rds
        remote_repository: https://github.com/GuillaumeFalourd/repo1
        access_token: ${{ secrets.ACCESS_TOKEN }}
        force: true
